"""create group invitations table

Revision ID: a54c6ba18a02
Revises: 31c420c1dd83
Create Date: 2026-10-09 20:56:39.396150

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "a54c6ba18a02"
down_revision: Union[str, Sequence[str], None] = "31c420c1dd83"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "group_invitations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("group_id", sa.UUID(), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=False),
        sa.Column("token", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["created_by_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["group_id"], ["groups.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token"),
    )
    op.create_index(
        op.f("ix_group_invitations_created_by_id"),
        "group_invitations",
        ["created_by_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_group_invitations_group_id"),
        "group_invitations",
        ["group_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_group_invitations_group_id"), table_name="group_invitations")
    op.drop_index(
        op.f("ix_group_invitations_created_by_id"), table_name="group_invitations"
    )
    op.drop_table("group_invitations")
    # ### end Alembic commands ###
